ci: fixed build error due to package conflict
Run npm run ci:all

> myf-tradeflow-core@0.5.0 ci:all
> npm ci && cd frontend && npm ci && cd ../backend && npm ci

added 41 packages, and audited 42 packages in 3s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 313 packages, and audited 314 packages in 6s

49 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm error code EUSAGE
npm error
npm error `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm error
npm error Invalid: lock file's better-sqlite3@11.10.0 does not satisfy better-sqlite3@12.4.6
npm error
npm error Clean install a project
npm error
npm error Usage:
npm error npm ci
npm error
npm error Options:
npm error [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm error [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm error [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
npm error [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
npm error [--no-bin-links] [--no-fund] [--dry-run]
npm error [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm error [--workspaces] [--include-workspace-root] [--install-links]
npm error
npm error aliases: clean-install, ic, install-clean, isntall-clean
npm error
npm error Run "npm help ci" for more info
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-11-27T19_05_11_853Z-debug-0.log
Error: Process completed with exit code 1.